### ISSUE TITLE
The link to the demo shows a Bad Gateway error

### ISSUE THREAD

**Issue by UniversusTech** [StretchShop/StretchShop#68]
On the Readme and the official website, the link to try the demo : https://demo.stretchshop.app/ 
leads to a Bad Gateway Error
![Bad Gateway for demo](https://github.com/StretchShop/StretchShop/assets/29806322/026a96aa-470e-41ec-990f-23779d50e721)

**Comment by Wradgio** [comment]
Thank you for noticing, the issue was fixed. It was related to changes in the Node.js container and how it handles 0.0.0.0, 127.0.0.1 and localhost. If you get into the same issue, you must set the IP env variable to 0.0.0.0
